"""empty message

Revision ID: 53a50d07dc79
Revises: 9b62d2066348
Create Date: 2022-11-03 14:38:35.519971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a50d07dc79'
down_revision = '9b62d2066348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('is_listed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'is_listed')
    # ### end Alembic commands ###
