"""empty message

Revision ID: 9b62d2066348
Revises: a2394fb22a26
Create Date: 2022-11-03 14:18:14.370565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b62d2066348'
down_revision = 'a2394fb22a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'agent_id')
    # ### end Alembic commands ###
