"""empty message

Revision ID: cc24c6026f2f
Revises: 14c78d22ccc7
Create Date: 2022-11-04 10:47:47.819389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc24c6026f2f'
down_revision = '14c78d22ccc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit', sa.Column('next_payment_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unit', 'next_payment_date')
    # ### end Alembic commands ###
